baseURL = 'https://drupal.merkle.com/'
languageCode = 'en'
title = 'Merkle Drupal & Acquia Blog'
theme = 'beautifulhugo'

[Params]
  homeTitle = 'Merkle Drupal & Acquia Blog'
  subtitle = "Merkle developers blog about Drupal and Acquia."
  mainSections = ["post","posts"]
  logo = "img/Merkle_Druplicon.svg"
  favicon = "img/favicon.ico"
  since = 2023
  dateFormat = "02. January 2006"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true

[Author]
  name = "Merkle Drupal Team"
  website = "https://www.merkle.com/dach/en/services/drupal"
  email = "drupal@merkle.com"
  github = "https://github.com/merkle-open"
  linkedin = "https://www.linkedin.com/company/merkle-dach"
  instagram = "https://www.instagram.com/merkledach/"
  drupal = "https://www.drupal.org/merkle"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
