baseURL = 'https://drupal.merkle.com/'
languageCode = 'en'
title = 'Merkle Drupal & Acquia Blog'
theme = 'beautifulhugo'

[Params]
  subtitle = "Merkle developers blog about Drupal and Acquia."
  mainSections = ["post","posts"]
  logo = "img/favicon-180x180.png"
  favicon = "img/favicon.ico"
  dateFormat = "29. November 2023"
  commit = false
  rss = true
  comments = false
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = false
  delayDisqus = false
  showRelatedPosts = true

[Author]
  name = "Merkle Drupal Team"
  website = "https://www.merkle.com/dach/"
  email = "drupal@merkle.com"
  github = "https://github.com/merkle-open"
  linkedin = "https://www.linkedin.com/company/merkle-dach"
  instagram = "https://www.instagram.com/merkledach/"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
